webserver/rolls/urls.py
from django.urls import path
from . import views



urlpatterns=[
    path('', views.rolls, name='home'),
    
    path('documentation', views.documentation, name="documentation"),
    path('dataset', views.dataset, name="dataset"),
    path('contact', views.contact, name="contact"),
    path('correlation_analysis', views.correlation_analysis, name= 'correlation_analysis'), 
   
    path('deseq2', views.deseq2, name='deseq2'),
    path('differential_expression', views.differential_expression, name= 'differential_expression'),
    path('diff_exp_single_tumor', views.diff_exp_single_tumor, name= 'diff_exp_single_tumor'),
    path('get-features/', views.get_features, name='get_features'),  # L'URL per la richiesta AJAX
    path('gene-suggestions/', views.gene_suggestions, name='gene_suggestions'),

    path('differential_expression_protein', views.differential_expression_protein, name= 'differential_expression_protein'),
    path('diff_exp_single_tumor_protein', views.diff_exp_single_tumor_protein, name= 'diff_exp_single_tumor_protein'),
    path('protein_suggestions/', views.protein_suggestions, name='protein_suggestions'),
       
    path('overall_survival', views.overall_survival, name= 'overall_survival'),
    path('OS_pathway', views.os_pathway, name= 'OS_pathway'),
    path('pathwayPROVA', views.pathwayPROVA, name='pathwayPROVA'),
    path('pathway_suggestions/', views.pathway_suggestions, name='pathway_suggestions'),

    path('rna_interactor',views.correlation_analysis, name= 'rna_interactor'),
    path('OS_interaction', views.os_interaction, name='OS_interaction'),
    
    path('tumor_mutation_analysis/', views.tumor_mutation_analysis, name='tumor_mutation_analysis'),
    path('tumor_oncoplot/', views.tumor_oncoplot, name='tumor_oncoplot'),
    path('somatic_interaction_analysis/', views.somatic_interaction_analysis, name='somatic_interaction_analysis'),
    path('gene_mutation_analysis/', views.gene_mutation_analysis, name='gene_mutation_analysis'),
    path('de_mut/', views.de_mut, name='de_mut'),
    path('de_mut_clinical_feature/', views.de_mut_clinical_feature, name='de_mut_clinical_feature'),
    path('gene_symbol_suggestions/', views.gene_symbol_suggestions, name='gene_symbol_suggestions'),
    path('survival_with_gene_mutation_status/', views.survival_with_gene_mutation_status, name='survival_with_gene_mutation_status'),
    path('get-features_R/', views.get_features_R, name='get_features_R'),  # L'URL per la richiesta AJAX


    path('deconvolution/', views.deconvolution,name='deconvolution'),
    path('corr_cell_pathway/', views.corr_cell_pathway,name='corr_cell_pathway'),

    #path('download_zip/', views.download_zip, name='download_zip'),
    path('download_zip/<str:subdirectory>/<str:zip_name>/', views.download_zip, name='download_zip'),

]

webserver/webserver/urls.py
from django.contrib import admin
from django.urls import path, include  
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('rolls.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webserver/rolls/models.py
from django.db import models

# Create your models here.

TUMOR=[
    (None,'Choice..'),
    ('ACC','ACC'),
    ('BLCA','BLCA'),
    ('BRCA','BRCA'),
    ('CESC','CESC'),
    ('CHOL','CHOL'),
    ('COAD','COAD'),
    ('DLBC','DLBC'),
    ('ESCA','ESCA'),
    ('GBM','GBM'),
    ('HNSC','HNSC'),
    ('KICH','KICH'),
    ('KIRC','KIRC'),
    ('KIRP','KIRP'),
    ('LGG','LGG'),
    ('LIHC','LIHC'),
    ('LUAD','LUAD'),
    ('LUSC','LUSC'),
    ('MESO','MESO'),
    ('OV','OV'),
    ('PAAD','PAAD'),
    ('PCPG','PCPG'),
    ('PRAD','PRAD'),
    ('READ','READ'),
    ('SARC','SARC'),
    ('SKCM','SKCM'),
    ('STAD','STAD'),
    ('TGCT','TGCT'),
    ('THCA','THCA'),
    ('THYM','THYM'),
    ('UCEC','UCEC'),
    ('UCS','UCS'),
    ('UVM','UVM')]

#rimosso MESO di cui non abbiamo i dati mutazionali
TUMOR_MUTATION=[ 
    (None,'Choice..'),
    ('ACC','ACC'),
    ('BLCA','BLCA'),
    ('BRCA','BRCA'),
    ('CESC','CESC'),
    ('CHOL','CHOL'),
    ('COAD','COAD'),
    ('DLBC','DLBC'),
    ('ESCA','ESCA'),
    ('GBM','GBM'),
    ('HNSC','HNSC'),
    ('KICH','KICH'),
    ('KIRC','KIRC'),
    ('KIRP','KIRP'),
    ('LGG','LGG'),
    ('LIHC','LIHC'),
    ('LUAD','LUAD'),
    ('LUSC','LUSC'),
    ('OV','OV'),
    ('PAAD','PAAD'),
    ('PCPG','PCPG'),
    ('PRAD','PRAD'),
    ('READ','READ'),
    ('SARC','SARC'),
    ('SKCM','SKCM'),
    ('STAD','STAD'),
    ('TGCT','TGCT'),
    ('THCA','THCA'),
    ('THYM','THYM'),
    ('UCEC','UCEC'),
    ('UCS','UCS'),
    ('UVM','UVM')]

FEATURES=[
    (None,'Choice..'),
    ('gender','Gender'),
    ('age_at_initial_pathologic_diagnosis','Age'),
    ('radiation_therapy','Radiation therapy'),
    ('patient_status','Patient status'),
    ('diabetes', 'Diabetes'),
    ('tobacco_smoking_history','Tobacco smoking history'),
    ('menopause_status','Menopause status'),
    ('alcohol_history_documented','Alcohol history documented'),
    ('pathologic_stage','Pathologic stage'),
    ]

FEATURE_R=[
    (None,'Please select a tumor type first'),
    ('gender','Gender'),
    ('alcohol_history_documented','Alcohol history documented'),
    # ('history_of_diabetes', 'Diabetes'),
    ('radiation_therapy','Radiation therapy'),
    ('person_neoplasm_cancer_status','Neoplasm cancer status'),
    ]

CHOICE_FEATURE =[
    ('Menopause status',(
        ('BRCA','BRCA'),
        ('OV','OV'),
        )
    )
]



class Analisi(models.Model):
    gene= models.CharField(
        max_length=20,)
    
    miRNA= models.CharField(
        max_length=20,)

    tumor=models.CharField(
        max_length=10,
        choices= TUMOR,
        default='Choice..',)

    feature=models.CharField(
        max_length=50,
        choices= FEATURES,
        default= 'Choice..',)
        

class Analisi_mutation(models.Model):
    gene= models.CharField(
        max_length=20,)
    
    tumor=models.CharField(
        max_length=10,
        choices= TUMOR_MUTATION,
        default='Choice..',)

    feature=models.CharField(
        max_length=50,
        choices= FEATURE_R,
        default= 'Choice..',) 

    NUMBER_CHOICES = [
        (10, '10'),
        (15, '15'),
        (20, '20'),
        (25, '25'),
    ]
    number = models.IntegerField(choices=NUMBER_CHOICES, default=10)

    feature_selected=models.CharField(
        max_length=50,
        default= 'Choice..',)

#class Downloadfileszip(models.Model)

#class link(models.Model):
#    url=models.TextField()


class Gene(models.Model):
    gene= models.CharField(max_length=100)


class Pathway(models.Model):
    pathway= models.CharField(max_length=100)

class Protein(models.Model):
    protein= models.CharField(max_length=100)

class Gene_symbol(models.Model):
    gene_symbol= models.CharField(max_length=100)

webserver/rolls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from subprocess import run,PIPE
import sys
from matplotlib import image
from rolls.forms import Gene, deconvolution_form,FormMutationChoice,featuremutationform,formcorrelation,Analisiform_protein,Analisiformcompleto_protein,formSurvival,Analisiform, Deseq2form, Analisiform1, Analisiformcompleto, Analisi_interaction,Analisipath,tumorGeneform,FormTumorMutation
import os
from django.http import StreamingHttpResponse
from wsgiref.util import FileWrapper
import mimetypes
from shutil import make_archive
import time
import os.path
from django.conf import settings
import shutil
import csv
import pandas as pd
from decimal import Decimal
from django.http import JsonResponse
from rolls.models import Gene,Pathway,Protein, Gene_symbol
from django.http import FileResponse, HttpResponseNotFound
import subprocess


import json
import configparser
from pathlib import Path

#richiamo conf.ini
config = configparser.ConfigParser()
script_dir = Path(__file__).parent

# Costruisci il percorso relativo al file di configurazione
config_file = script_dir.parent.parent / 'webserver' / 'webserver' / 'conf.ini'

config.read(config_file) 
#directory base
output_data = config['Paths']['output_data']
base_dir = config.get('Paths', 'base_dir', fallback='')
output_data_Table=config['Paths']['output_data_Table']

def get_full_path(relative_path):
    return os.path.join(base_dir, relative_path)

parametri={
    'patient_status':'Tumor vs Ctrl',
    'gender':'Female vs Male',
    'pathologic_stage': 'Stage III-IV vs Stage I-II',
    'radiation_therapy': 'YES vs NO',
    'diabetes': 'YES vs NO',
    'tobacco_smoking_history': 'Smoker vs Non_Smoker',
    'menopause_status':'Post-menopause vs Pre-menopause',
    'alcohol_history_documented': 'YES vs NO',
    'age_at_initial_pathologic_diagnosis': 'Above the median vs Below the median' ,
}




def rolls(request):
    count = get_counter()
    return render(request, 'rolls/home.html',{'count': count,})

def documentation(request):
    count = get_counter()
    return render(request, 'rolls/documentation.html',{'count': count,})

def read_table(file_path):
    txt_data = []

    df = pd.read_csv(file_path, sep='\t',dtype=str)
    #print(df)

    txt_data.append(df.columns.tolist())
    
    # Itera sulle righe del DataFrame e aggiungi ogni riga come lista
    for index, row in df.iterrows():
        txt_data.append(row.tolist())
    return(txt_data)


def dataset(request):
    count = get_counter()
    file_path = os.path.join(output_data_Table,'table','campioni_TCGA.txt')
    file_path_genetype=os.path.join(output_data_Table,'table','gene_type.txt')
    file_feature_tumor=os.path.join(output_data_Table,'table','Features_tumor.txt')
    file_tumor=os.path.join(output_data_Table,'table','tumor_abbreviations.txt')
    file_parameters=os.path.join(output_data_Table,'table','feature_parameters.txt')

    txt_data_clinical=read_table(file_path)

    txt_data_typegene=read_table(file_path_genetype)   
    txt_feature_tumor= read_table(file_feature_tumor)
    txt_tumor= read_table(file_tumor) 
    txt_parameters=read_table(file_parameters)
    return render(request, 'rolls/dataset.html', {
        'dati': txt_data_clinical, 
        'dati_genetype':txt_data_typegene,
        'dati_feature':txt_feature_tumor,
        'dati_tumor':txt_tumor,
        'dati_parametri':txt_parameters,
        'count': count,
 })


def contact(request):
    count = get_counter()
    return render(request, 'rolls/contact.html',{'count': count,})

def yourdataset(request):
    return render(request,'rolls/yourdataset.html')


##########################################
# Function for autocomplete
def gene_suggestions(request):
    if 'term' in request.GET:
        qs = Gene.objects.filter(gene__istartswith=request.GET.get('term'))
        genes = sorted(qs.values_list('gene', flat=True), key=len)[:10]  # Ordina per lunghezza e limita a 10
        return JsonResponse(genes, safe=False)
    
    
def pathway_suggestions(request):
    if 'term' in request.GET:
        qs = Pathway.objects.filter(pathway__icontains=request.GET.get('term'))[:20]  # Limita i risultati a 10
        pathways = list(qs.values_list('pathway', flat=True))
        return JsonResponse(pathways, safe=False)
    
def protein_suggestions(request):
    if 'term' in request.GET:
        qs = Protein.objects.filter(protein__istartswith=request.GET.get('term'))
        protein = sorted(qs.values_list('protein', flat=True), key=len)[:10]  # Ordina per lunghezza e limita a 20
        return JsonResponse(protein, safe=False)
    
def gene_symbol_suggestions(request):
    if 'term' in request.GET:
        qs = Gene_symbol.objects.filter(gene_symbol__istartswith=request.GET.get('term'))
        gene_symbol = sorted(qs.values_list('gene_symbol', flat=True), key=len)[:10]  # Ordina per lunghezza e limita a 20
        return JsonResponse(gene_symbol, safe=False)
##########################################



#contatore per visualizzare quante analisi sono state effettuate
counter_file = 'analysis_counter.txt'
def get_counter():
    # Se il file non esiste, ritorna 0 come valore di default
    if not os.path.exists(counter_file):
        return 0
    
    # Leggi il valore del contatore dal file
    with open(counter_file, 'r') as f:
        count = int(f.read().strip())
    
    return count

# Funzione per aggiornare il contatore
def increment_counter():
        # Se il file non esiste, crealo con valore iniziale 0
        if not os.path.exists(counter_file):
            with open(counter_file, 'w') as f:
                f.write('0')
        
        # Leggi il valore corrente del contatore, incrementa e riscrivilo
        with open(counter_file, 'r+') as f:
            count = int(f.read().strip())
            count += 1
            f.seek(0)
            f.write(str(count))
            f.truncate()
        return count
####################################################################################



TUMOR_FEATURE_MAPPING = {
    "ACC":['age_at_initial_pathologic_diagnosis','gender','pathologic_stage','radiation_therapy'],
    "BLCA":['age_at_initial_pathologic_diagnosis','gender','pathologic_stage','patient_status','radiation_therapy','tobacco_smoking_history'],
    "BRCA":['age_at_initial_pathologic_diagnosis','menopause_status','pathologic_stage','patient_status','radiation_therapy'],
    "CESC":['age_at_initial_pathologic_diagnosis','menopause_status','radiation_therapy','tobacco_smoking_history'],
    "CHOL":['age_at_initial_pathologic_diagnosis','gender','pathologic_stage'],
    "COAD":['age_at_initial_pathologic_diagnosis','gender','pathologic_stage','patient_status','radiation_therapy'],
    "DLBC":['age_at_initial_pathologic_diagnosis','gender','radiation_therapy'],
    "ESCA":['age_at_initial_pathologic_diagnosis','alcohol_history_documented','gender','pathologic_stage','radiation_therapy','tobacco_smoking_history'],
    "GBM":['age_at_initial_pathologic_diagnosis','gender','radiation_therapy'],
    "HNSC":['age_at_initial_pathologic_diagnosis','alcohol_history_documented','gender','pathologic_stage','patient_status','radiation_therapy','tobacco_smoking_history'],
    "KICH":['age_at_initial_pathologic_diagnosis','gender','pathologic_stage','patient_status','tobacco_smoking_history'],
    "KIRC":['age_at_initial_pathologic_diagnosis','gender','pathologic_stage','patient_status','radiation_therapy','tobacco_smoking_history'],
    "KIRP":['age_at_initial_pathologic_diagnosis','gender','pathologic_stage','patient_status','radiation_therapy','tobacco_smoking_history'],
    "LGG":['age_at_initial_pathologic_diagnosis','gender','radiation_therapy'],
    "LIHC":['age_at_initial_pathologic_diagnosis','gender','pathologic_stage','patient_status','radiation_therapy'],
    "LUAD":['age_at_initial_pathologic_diagnosis','gender','pathologic_stage','patient_status','radiation_therapy','tobacco_smoking_history'],
    "LUSC":['age_at_initial_pathologic_diagnosis','gender','pathologic_stage','patient_status','radiation_therapy','tobacco_smoking_history'],
    "MESO":['age_at_initial_pathologic_diagnosis','gender','pathologic_stage','radiation_therapy'],
    "OV":['age_at_initial_pathologic_diagnosis','radiation_therapy'],
    "PAAD":['age_at_initial_pathologic_diagnosis','alcohol_history_documented','gender','pathologic_stage','radiation_therapy','tobacco_smoking_history'],
    "PCPG":['age_at_initial_pathologic_diagnosis','gender','radiation_therapy'],
    "PRAD":['age_at_initial_pathologic_diagnosis','patient_status','radiation_therapy'],
    "READ":['age_at_initial_pathologic_diagnosis','gender','pathologic_stage','radiation_therapy'],
    "SARC":['age_at_initial_pathologic_diagnosis','gender','radiation_therapy'],
    "SKCM":['age_at_initial_pathologic_diagnosis','gender','pathologic_stage','radiation_therapy'],
    "STAD":['age_at_initial_pathologic_diagnosis','gender','pathologic_stage','patient_status','radiation_therapy'],
    "TGCT":['age_at_initial_pathologic_diagnosis','pathologic_stage','radiation_therapy'],
    "THCA":['age_at_initial_pathologic_diagnosis','gender','pathologic_stage','patient_status','radiation_therapy'],
    "THYM":['age_at_initial_pathologic_diagnosis','gender','radiation_therapy'],
    "UCEC":['age_at_initial_pathologic_diagnosis','diabetes','menopause_status','patient_status','radiation_therapy'],
    "UCS":['age_at_initial_pathologic_diagnosis','diabetes','radiation_therapy'],
    "UVM":['age_at_initial_pathologic_diagnosis','gender','pathologic_stage','radiation_therapy'],
}


def get_features(request):
    # Ottieni il valore del tumore selezionato
    tumor = request.GET.get('tumor')
    
    # Ottieni le feature corrispondenti dal dizionario
    features = TUMOR_FEATURE_MAPPING.get(tumor, [])
    
    # Restituisci le feature come tuple (valore, etichetta)
    feature_list = [(feature, feature) for feature in features]
    

webserver/rolls/templates/rolls/contact.html
{%extends 'rolls/layoutpagine.html' %}
{% load static %}
{%block content%}
<h2 style="color:navy">PANDA</h2>   
    <div class="conteiner my-3" style="position: center;">
        <p>PANDA (PAN cancer data analysis web tool) is a Bioinformatics Tool for statistical analysis of tumor gene expression.
           This web server provides tools for analyzing RNAseq data collected by TCGA. The available analyses use clinical data to perform differential gene expression and overall survival with different options.</p>
        <br>
        <h4> How to cite PANDA </h4>
        <p>If you use PANDA, even just for preliminary analysis, please cite: insert citation</p>
        <br>
        <h4> Contacts </h4>
        
           
        <p> For questions, support, bug reports, proposals, cooperations or any other communication, feel free to contact:
        <p><b>Gerardo Pepe</b> (Conceptualized and designed the study, supervised the development of the webserver and implemented the scripts for data analysis tools): <a href="mailto:gerardo.pepe@uniroma2.it">gerardo.pepe@uniroma2.it</a></p>
        <p><b>Chiara Notturno Granieri</b> (implemented both back-end and front-end components and scripts for data analysis tools): <a href="mailto:chiara.notturno@gmail.com">chiara.notturno@gmail.com</a></p>
        <p><b>Romina Appierdo</b> (worked on the implementation of scripts for data analysis tools): <a href="mailto:romina.appierdo@uniroma2.it">romina.appierdo@uniroma2.it</a></p>
        
        <br><br>
        Centre for Molecular Bioinformatics
        <br>
        <b>Prof. Manuela Helmer-Citterich</b>
        <br>
        <b>Prof. Pier Federico Gherardini</b>
        <br>
        Tor Vergata University
        <br>
        Rome-Italy
    </div> 
        

  

   
{%endblock%}
 

webserver/rolls/templates/rolls/de_mut_clinical_feature.html
{%extends 'rolls/layoutpagine.html' %}
{%load crispy_forms_tags%}
{%block content%}
{% load static %}
<h4 style="color:navy">Mutation Analyses</h4>
<h2> Differentially Mutated Gene by Clinical Feature</h2>
   
    <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapsedescription" role="button" aria-expanded="false" aria-controls="collapsedescription">
      Description
    </a>
    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      Example
    </button>
  </p>
  <div class="collapse" id="collapsedescription">
    <div class="card card-body">
      <h4> Differentially Mutated Gene by Clinical Feature</h4>
        <p>
            This analysis compares two cohorts of cancer patients using genomic data from TCGA to analyze genetic mutations by stratifying patients by clinical characteristics. It generates a forest plot highlighting the 10 genes with the most significant mutations between the groups, showing differences in mutational profiles. It also produces a coBarplot illustrating the distribution of mutations in the two groups. 
        </p>
        <p>
            These graphs provide a clear view of mutational differences, helping to identify key genes associated with different clinical responses. The results are also saved in a CSV file for further analysis.
        </p>
        <p>For more details go to <a href="{% url 'documentation' %}" target="_blank">PANDA Documentation</a></p>
    </div>
  </div>

  <div class="row my-3">
    <div class="col-sm-3 my-3">
        <form method="post" id="analysis-form">
            {%csrf_token%}
            {{form|crispy}}         
            <div class="d-grid gap-2 d-md-flex justify-content-md">
                <button class="btn btn-primary me-md-2 my-3" type="Submit" name="Submit">Submit</button>
            </div>
        </form>
      </div>
      <div class="col mx-3" style="border:1px; border-left-style: solid; border-color:rgba(0, 0, 128, 0.301)">
        <div class="collapse" id="collapseExample">
        <div class="card card-body">
          <p class="text-center" >Example: </p>
          <img src= "{%static 'media/examples/de_clinical.png' %}" width="750">
        </div> 
        </div>
        {%if go == 'Valid' %}        
        <h3 class="d-flex justify-content-between align-items-center">
          <span>Results</span>
          
          <div class="text-end">
              <span style="font-size: 14px;">Click here to download all the results of this analysis</span>
              <a href="{% url 'download_zip' subdirectory=dir zip_name='results.zip' %}" download target="blank" title="Click here to download all the results of this analysis">
                  <button class="btn btn-sm"><i class="fa-solid fa-download"></i></button>
              </a>
          </div>
      </h3>
        <hr>
        <div class="row">
            <div class="col mx-3">
              
              <p><b>Tumor:</b> {{tumor}}</p>
              <p><b>Feature selected:</b> {{feature}}</p>
              <!-- <p><b>Parameters compared:</b> {{parametri}}</p> -->
              
            </div>
          
          <div class="row">
            <div class="mb-3 rounded" style="max-width: 800px;text-align: center; ">
              <a href="{%static image_forest%}" target="_blank"><img src= '{%static image_forest %}' width="700"></a>
            </div>
            
            <!-- <p>You can download the results for all genes with their p-value here <a href="{% static table %}" download target="_blank"><button class="btn"><i class="fa-solid fa-download"></i></button></a></p> -->
            <br>
            <br>

            <div class="mb-3 rounded" style="max-width: 800px;text-align: center; ">
              <a href="{%static image_coBarplot%}" target="_blank"><img src= '{%static image_coBarplot %}' width="700"></a>
            </div>

          </div> 
      
     
        </div>
      </div>
        {%endif%}
  
        {%if go == 'error'%}
        <div class="alert alert-danger text-center" role="alert">
          <h5>There are no mutations for this gene {{gene}} in the tumor {{tumor}}</h5>
          
          
        </div> 


        {%endif%}
      </div>
      
    </div>


   <!-- Includi jQuery UI e il suo CSS -->
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<!-- Script per il suggerimento con jQuery UI
<script type="text/javascript">
  $(document).ready(function() {
    $('#gene_symbol-input').autocomplete({
      source: function(request, response) {
        $.ajax({
          url: "{% url 'gene_symbol_suggestions' %}",  // L'URL che abbiamo aggiunto
          data: {
            'term': request.term  // Il testo digitato dall'utente
          },
          success: function(data) {
            response(data);  // Restituisci i risultati all'autocomplete
          }
        });
      },
      minLength: 1,  // Numero minimo di caratteri per avviare l'autocomplete
    });
  });
</script> -->


<!-- <script>
  $(document).ready(function() {
      $('#id_tumor').change(function() {
          var tumor = $(this).val();  // Ottieni il tumore selezionato
          
          // Invia la richiesta AJAX per ottenere le feature corrispondenti
          $.ajax({
              url: "{% url 'get_features_R' %}",  // Assicurati che l'URL punti alla vista giusta
              data: {
                  'tumor': tumor  // Passa il tumore selezionato come parametro
              },
              success: function(data) {
                  // Svuota il campo feature
                  $('#feature-select').empty();

                  // Aggiungi le nuove opzioni delle feature
                  $.each(data, function(index, feature) {
                      $('#feature-select').append(
                          $('<option></option>').val(feature[0]).html(feature[1])
                      );
                  });
              }
          });
      });
  });
</script> -->

<!-- new selezione prima tumore e dopo feature -->

<script>
  $(document).ready(function() {
      // Disabilita il campo feature all'inizio
      $('#feature-select').prop('disabled', true);

      $('#id_tumor').change(function() {
          var tumor = $(this).val();  // Ottieni il tumore selezionato
          
          // Nascondi il messaggio di errore quando cambia la selezione del tumore
          $('#tumor-error').hide();

          // Verifica se è stato selezionato un valore per il tumore
          if (tumor) {
              // Invia la richiesta AJAX per ottenere le feature corrispondenti
              $.ajax({
                  url: "{% url 'get_features_R' %}",  // Assicurati che l'URL punti alla vista giusta
                  data: {
                      'tumor': tumor  // Passa il tumore selezionato come parametro
                  },
                  success: function(data) {
                      // Svuota il campo feature
                      $('#feature-select').empty();

                      // Aggiungi le nuove opzioni delle feature
                      $.each(data, function(index, feature) {
                          $('#feature-select').append(
                              $('<option></option>').val(feature[0]).html(feature[1])
                          );
                      });

                      // Abilita il campo feature dopo il caricamento delle opzioni
                      $('#feature-select').prop('disabled', false);
                  }
              });
          } else {
              // Se nessun tumore è selezionato, disabilita il campo feature e mostra un messaggio di errore
              $('#feature-select').prop('disabled', true);
              $('#feature-select').empty();  // Svuota eventuali opzioni precedenti
              $('#tumor-error').show(); // Mostra il messaggio di errore
          }
      });

      // Se l'utente prova a interagire con feature-select quando è disabilitato
      $('#feature-select').focus(function() {
          if ($('#feature-select').prop('disabled')) {
              $('#tumor-error').show(); // Mostra il messaggio di errore
          }
      });
  });
</script>

{%endblock%}
    